library(dplyr)
setwd("F:/Berkeley/R_Analysis/Module_15_Challenge/")
mecha <- read.csv(file='MechaCar_mpg.csv', check.names=F,stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha))
