library(dplyr)
setwd("F:/Berkeley/R_Analysis/Module_15_Challenge/")
mecha <- read.csv(file='MechaCar_mpg.csv', check.names=F,stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=mecha))
suspension <- read.csv(file='Suspension_Coil.csv', check.names=F, stringsAsFactors = F)
sus_sum <- suspension %>% summarize(Mean =mean(PSI), Median =median(PSI), Variance = var(PSI), SD = sd(PSI), .groups = 'keep')
lot_sum <- suspension %>% group_by(Manufacturing_Lot) %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI), .groups ='keep')
